AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: "AWS resources for a serverless security system"

Parameters:
  PresignUrlExpirationTime:
    Type: Number
    Description: The number (in seconds) that presigned url's are valid for. Note that this can is the default and can be later updated within the user interface # TODO - implement that functionality
    Default: 3600

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain TODO - restore this

  S3BucketClientAccessManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'Serverless-Security-System-S3-Write-Access-Policy-${AWS::StackName}'
      Description: 'Managed policy that allows write (and limited read) access to the S3 bucket used for the Serverless-Security-System'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: [ 's3:PutObject', 's3:PutObjectAcl' ]
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'

  S3BucketAPIAccessManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'Serverless-Security-System-S3-read-write-delete-access-Policy-${AWS::StackName}'
      Description: 'Managed policy that allows read/write/delete access to the S3 bucket used for the Serverless-Security-System'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: [ 's3:ListObjects*', 's3:ListBucket' ]
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}'
          - Effect: Allow
            Action: [ 's3:PutObject', 's3:PutObjectAcl' ]
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/configuration/*'
          - Effect: Allow
            Action: [ 's3:Describe*', 's3:Get*' ]
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'

  IAMUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: !Sub '${AWS::StackName}-client-user'
      Path: '/apps/'
      ManagedPolicyArns: 
        - !Ref S3BucketClientAccessManagedPolicy
      Tags: 
        - Key: 'Description'
          Value: 'IAM User for accessing S3 bucket for Serverless-Security-System.'

  IAMPermissionsBoundary:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'IAM-S3-Only-PermissionsBoundary-${AWS::StackName}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*'
      Users:
        - !Ref IAMUser

  IAMUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref IAMUser

  AccessKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}-client-user-access-key-secret'
      Description: !Sub 'Access Key Secret for ${IAMUser} user'
      SecretString: !Sub '{"AccessKeyId":"${IAMUserAccessKey}","SecretAccessKey":"${IAMUserAccessKey.SecretAccessKey}"}'


  # Serverless API composed of lambda functions
  APIFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: !Sub 'Role for the lambda functions that make up the serverless API for ${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns: 
        - !Ref S3BucketAPIAccessManagedPolicy
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /

  GetVideosLambdaFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/api/
      Handler: app.get_videos
      Runtime: python3.8
      PackageType: Zip
      Environment:
        Variables:
          S3_BUCKET: !Ref S3Bucket
          PRESIGN_URL_EXPIRATION_TIME: !Ref PresignUrlExpirationTime
      Role: !GetAtt APIFunctionRole.Arn
      Events:
        Get:
          Type: Api
          Properties:
            Path: /videos/{filter}
            Method: GET
      Timeout: 10


Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: The name of the stacks S3 bucket where videos are stored.

