version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: 'cloud/ui/'
    schedule:
      interval: monthly
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - cal-overflow
    assignees:
      - cal-overflow
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: 'cloud/ui/'
    schedule:
      interval: monthly
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - cal-overflow
    assignees:
      - cal-overflow
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
