AWSTemplateFormatVersion: 2010-09-09
Description: "AWS resources for a serverless security system"

Parameters:
  StackS3Bucket:
    Type: String
    Description: The name of the Stack S3 bucket (for storing lambda layer & source code)

  VideoProcessFunctionS3Key:
    Type: String
    Description: The Object Key of the source code for the Video Process Function S3 key (within the given StackS3Bucket)

  OpenCVLambdaLayerS3Key:
    Type: String
    Description: The Object Key of the Open-CV Lambda Layer (zip) S3 key (within the given StackS3Bucket)


Resources:
  OpenCVLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Description: Open-CV layer essential for running open-cv python in Lambda.
      Content:
        S3Bucket: !Ref StackS3Bucket
        S3Key: !Ref OpenCVLambdaLayerS3Key
      CompatibleRuntimes:
        - python3.8



  S3BucketUploadOnlyAccessManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 'Serverless-Security-System-S3-Write-Access-Policy'
      Description: 'Managed policy that allows write access to the S3 bucket used for the Serverless-Security-System'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: [ 's3:PutObject', 's3:PutObjectAcl' ]
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'

  IAMUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: 'security-system-client'
      Path: '/apps/'
      ManagedPolicyArns: 
        - !Ref S3BucketUploadOnlyAccessManagedPolicy
      Tags: 
        - Key: 'Description'
          Value: 'IAM User for uploading files to S3 bucket for Serverless-Security-System.'

  IAMPermissionsBoundary:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: 'IAM-S3-Only-PermissionsBoundary'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*'
      Users:
        - !Ref IAMUser

  IAMUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref IAMUser

  AccessKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: 'secury-system-client-user-access-key-secret'
      Description: !Sub 'Access Key Secret for ${IAMUser} user'
      SecretString: !Sub '{"AccessKeyId":"${IAMUserAccessKey}","SecretAccessKey":"${IAMUserAccessKey.SecretAccessKey}"}'



  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt ProcessVideosLambdaFn.Arn

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Action: 's3:GetObject'
            Effect: Allow
            Principal: '*'
            Resource: 
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'
 
  LambdaFnRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-LambdaFnRole'
      Description: !Sub "Execution role for the Process-Videos Lambda function in ${AWS::StackName}"
      ManagedPolicyArns:
        - !Ref LambdaFnPolicy
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
            - 'sts:AssumeRole'

  LambdaFnPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${AWS::StackName}-ProcessVideosLambdaFn-ManagedPolicy'
      Description: !Sub 'Managed Policy for the Process-Videos Lambda function in ${AWS::StackName}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: [ 's3:ListBucket' ]
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}'
          - Effect: Allow
            Action: [ 's3:GetObject', 's3:PutObject', 's3:PutObjectAcl', 's3:DeleteObject' ]
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'

  ProcessVideosLambdaFn:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref StackS3Bucket
        S3Key: !Ref VideoProcessFunctionS3Key
      Handler: app.handler
      Runtime: python3.8
      Layers:
        - !Ref OpenCVLambdaLayer
      Role: !GetAtt LambdaFnRole.Arn
      Environment:
        Variables:
          S3_BUCKET: !Ref S3Bucket
      Description: Lambda function that processes (keeps only significant) videos within the S3 bucket
      # TODO - potentially configure better cpu/memory resources

  LambdaS3BucketEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      SourceAccount: !Ref 'AWS::AccountId'
      FunctionName: !Ref ProcessVideosLambdaFn
      SourceArn: !GetAtt S3Bucket.Arn
      Principal: s3.amazonaws.com

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: The name of the stacks S3 bucket where videos are stored.

  # TODO - potentially remove this (I don't think it's being used anywhere)
  VideoProcessorLambdaFunctionName:
    Value: !Ref ProcessVideosLambdaFn
    Description: The name of the Lambda Function that performs the video processing.

