AWSTemplateFormatVersion: 2010-09-09
Description: "AWS resources for a serverless security system"


Resources:
  S3Bucket:
    Type: AWS::S3::Bucket

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Action: 's3:GetObject'
            Effect: Allow
            Principal: '*'
            Resource: 
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'

  S3BucketAccessManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 'Serverless-Security-System-S3-Write-Access-Policy'
      Description: 'Managed policy that allows write access to the S3 bucket used for the Serverless-Security-System'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: [ 's3:ListBucket' ]
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}'
          - Effect: Allow
            Action: [ 's3:GetObject', 's3:PutObject', 's3:PutObjectAcl' ]
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'

  IAMPermissionsBoundary:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: 'IAM-S3-Only-PermissionsBoundary'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*'
      Users:
        - !Ref IAMUser

  IAMUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: 'security-system-client'
      Path: '/apps/'
      ManagedPolicyArns: 
        - !Ref S3BucketAccessManagedPolicy
      # PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::aws:policy:${IAMPermissionsBoundary}'
      # Policies: 
      #   - Policy
      Tags: 
        - Key: 'Description'
          Value: 'IAM User for uploading files to S3 bucket for Serverless-Security-System.'


Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: The name of the stacks S3 bucket.

