name: Build and push docker image

on:
  push:
    tags:
      - v*

jobs:
  build-deploy-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup QEMU (for multi-architecture)
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx (for multi-architecture)
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: caloverflow
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Versions
        uses: actions/github-script@v4
        id: get_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            core.setOutput('no-v', no_v)

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: 'caloverflow/security-system-client:latest,caloverflow/security-system-client:${{ steps.get_version.outputs.no-v }}'
          platforms: linux/amd64,linux/arm64,linux/arm/v7

