name: Deploy AWS Resources

on:
  push:
    branches:
      - main
      - auto-delete-old-videos # TODO - remove
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  REGION: us-east-1
  STACK_NAME: security-system
  API_LAMBDA_FN_S3_KEY: lambda/api.zip
  UPLOAD_HANDLER_LAMBDA_FN_S3_KEY: lambda/upload_handler.zip
  ATTACH_S3_NOTIFICATION_TO_LAMBDA_LAMBDA_FN_S3_KEY: lambda/attach_s3_upload_event_upload_handler_trigger.zip
  STALE_VIDEO_REMOVER_LAMBDA_FN_S3_KEY: lambda/video_purger.zip


jobs:
   deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cloud
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: ${{ env.REGION }}
      
      - name: Deploy management-bucket stack
        run: |
          MANAGEMENT_BUCKET_STACK_NAME="$STACK_NAME-management-bucket-stack"

          sam deploy --region $REGION -t management-stack.template.yml --stack-name $MANAGEMENT_BUCKET_STACK_NAME
          STACK_MANAGEMENT_BUCKET=$(aws cloudformation describe-stacks --stack-name=$MANAGEMENT_BUCKET_STACK_NAME --region $REGION --query 'Stacks[0].Outputs[?OutputKey==`S3BucketName`].OutputValue' --output text)
          echo "STACK_MANAGEMENT_BUCKET=$STACK_MANAGEMENT_BUCKET" >> $GITHUB_ENV
          
      - name: Upload serverless api lambda function source code (to S3)
        run: |
          cd lambda/api
          zip tmp.zip requirements.txt *.py
          aws s3 cp tmp.zip s3://$STACK_MANAGEMENT_BUCKET/$API_LAMBDA_FN_S3_KEY

      - name: Upload upload-handler lambda function source code (to S3)
        run: |
          cd lambda/upload_handler
          zip tmp.zip requirements.txt *.py
          aws s3 cp tmp.zip s3://$STACK_MANAGEMENT_BUCKET/$UPLOAD_HANDLER_LAMBDA_FN_S3_KEY

      - name: Upload attach-s3-notifcation-to-lambda lambda function source code (to S3)
        run: |
          cd lambda/attach_s3_upload_event_upload_handler_trigger
          zip tmp.zip requirements.txt *.py
          aws s3 cp tmp.zip s3://$STACK_MANAGEMENT_BUCKET/$ATTACH_S3_NOTIFICATION_TO_LAMBDA_LAMBDA_FN_S3_KEY

      - name: Upload stale-video-remover lambda function source code (to S3)
        run: |
          cd lambda/video_purger
          zip tmp.zip requirements.txt *.py
          aws s3 cp tmp.zip s3://$STACK_MANAGEMENT_BUCKET/$STALE_VIDEO_REMOVER_LAMBDA_FN_S3_KEY

      - name: Deploy Security System stack
        run: |
          sam deploy --stack-name $STACK_NAME --region $REGION --s3-bucket $STACK_MANAGEMENT_BUCKET --parameter-overrides "StackManagementS3Bucket=$STACK_MANAGEMENT_BUCKET" "APILambdaFnS3Key=$API_LAMBDA_FN_S3_KEY" "UploadHandlerFunctionS3Key=$UPLOAD_HANDLER_LAMBDA_FN_S3_KEY" "AttachLambdaS3NotificationTriggerFunctionS3Key=$ATTACH_S3_NOTIFICATION_TO_LAMBDA_LAMBDA_FN_S3_KEY" "StaleVideoRemoverFunctionS3Key=$STALE_VIDEO_REMOVER_LAMBDA_FN_S3_KEY"
          BUCKET=$(aws cloudformation describe-stacks --stack-name=$STACK_NAME --region $REGION --query 'Stacks[0].Outputs[?OutputKey==`S3BucketName`].OutputValue' --output text)

          aws s3 cp settings.json s3://$BUCKET/configuration/

